{
 "title": "Pulsar Overview",
 "tags": [ "pulsar" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Topics Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_broker_topics_count{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_throughput_in_total{cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} - in"
    },
    {
     "expr": "sum(rate(pulsar_broker_throughput_out_total{cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} - out"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_message_rate_in_total{cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} - in"
    },
    {
     "expr": "sum(rate(pulsar_broker_message_rate_out_total{cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} - out"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cluster=\"$cluster\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\"}[1m])*100",
     "legendFormat": "{{instance}} - {{component}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} - {{component}}"
    }
   ]
  }
 ]
}