id: tailwind_config_template
name: Tailwind CSS Configuration
description: Template for Tailwind CSS configuration and theme customization
version: 1.0.0
category: frontend/styling
sections:
  - name: project_info
    description: Project information
    fields:
      - name: project_name
        type: STRING
        description: Name of the project
        required: true
        default_value: ""
        validation_rules:
          - rule_type: MIN_LENGTH
            expression: "1"
            error_message: "Project name cannot be empty"
      - name: tailwind_version
        type: STRING
        description: Tailwind CSS version
        required: true
        default_value: "3.3.3"
        validation_rules:
          - rule_type: PATTERN
            expression: "^\\d+\\.\\d+\\.\\d+$"
            error_message: "Version must follow semantic versioning"
  - name: customization
    description: Theme customization options
    fields:
      - name: custom_colors
        type: BOOLEAN
        description: Whether to customize the color palette
        required: true
        default_value: "true"
        validation_rules: []
      - name: color_palette
        type: OBJECT
        description: Custom color palette
        required: false
        default_value: |
          {
            "primary": {
              "50": "#f0f9ff",
              "100": "#e0f2fe",
              "200": "#bae6fd",
              "300": "#7dd3fc",
              "400": "#38bdf8",
              "500": "#0ea5e9",
              "600": "#0284c7",
              "700": "#0369a1",
              "800": "#075985",
              "900": "#0c4a6e",
              "950": "#082f49"
            },
            "secondary": {
              "50": "#f5f3ff",
              "100": "#ede9fe",
              "200": "#ddd6fe",
              "300": "#c4b5fd",
              "400": "#a78bfa",
              "500": "#8b5cf6",
              "600": "#7c3aed",
              "700": "#6d28d9",
              "800": "#5b21b6",
              "900": "#4c1d95",
              "950": "#2e1065"
            }
          }
        validation_rules: []
      - name: custom_fonts
        type: BOOLEAN
        description: Whether to customize the font families
        required: true
        default_value: "false"
        validation_rules: []
      - name: font_families
        type: OBJECT
        description: Custom font families
        required: false
        default_value: |
          {
            "sans": ["Inter", "ui-sans-serif", "system-ui"],
            "serif": ["Merriweather", "ui-serif", "Georgia"],
            "mono": ["JetBrains Mono", "ui-monospace", "monospace"]
          }
        validation_rules: []
      - name: custom_spacing
        type: BOOLEAN
        description: Whether to customize spacing scale
        required: true
        default_value: "false"
        validation_rules: []
      - name: custom_breakpoints
        type: BOOLEAN
        description: Whether to customize breakpoints
        required: true
        default_value: "false"
        validation_rules: []
  - name: plugins
    description: Tailwind plugins to use
    fields:
      - name: typography
        type: BOOLEAN
        description: Use @tailwindcss/typography plugin
        required: true
        default_value: "false"
        validation_rules: []
      - name: forms
        type: BOOLEAN
        description: Use @tailwindcss/forms plugin
        required: true
        default_value: "false"
        validation_rules: []
      - name: line_clamp
        type: BOOLEAN
        description: Use @tailwindcss/line-clamp plugin
        required: true
        default_value: "false"
        validation_rules: []
      - name: aspect_ratio
        type: BOOLEAN
        description: Use @tailwindcss/aspect-ratio plugin
        required: true
        default_value: "false"
        validation_rules: []
      - name: custom_plugins
        type: ARRAY
        description: Custom plugins to include
        required: false
        default_value: "[]"
        validation_rules: []
  - name: advanced
    description: Advanced configuration options
    fields:
      - name: jit_mode
        type: BOOLEAN
        description: Use JIT (Just-In-Time) mode
        required: true
        default_value: "true"
        validation_rules: []
      - name: purge_enabled
        type: BOOLEAN
        description: Enable content purging for production
        required: true
        default_value: "true"
        validation_rules: []
      - name: purge_content
        type: ARRAY
        description: Files to scan for class names
        required: false
        default_value: |
          [
            "./pages/**/*.{js,ts,jsx,tsx}",
            "./components/**/*.{js,ts,jsx,tsx}"
          ]
        validation_rules: []
      - name: dark_mode
        type: ENUM
        description: Dark mode strategy
        required: true
        default_value: "media"
        validation_rules:
          - rule_type: ENUM_VALUES
            expression: "media,class,false"
            error_message: "Dark mode must be one of media, class, or false"
