version: 3.8

services:

  # Project Service - Manages projects and spec sheets
  project_manager:
    build:
      context: ../src/services/project_manager
    environment:
      - SPEC_REGISTRY_URL=http://spec-registry:8000
      - EVENT_BUS_URL=pulsar://pulsar:6650
      - EVENT_AGGREGATOR_URL=http://event-aggregator:8080
    depends_on:
      - spec-registry
      - pulsar
      - event-aggregator
    networks:
      - spec-template-network
      - pulsar-network

  # Spec Registry Service
  spec-registry:
    build:
      context: ../src/services/spec_registry
      dockerfile: Dockerfile

    container_name: spec-registry
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
      - ENABLE_EVENTS=true
      - BASE_DIR=/app/storage
      - DB_CONNECTION_STRING=postgresql://database:5432/specdb
      - DB_SCHEMA=public
      - EVENT_AGGREGATOR_URL=http://event-aggregator:8080
    volumes:
      - spec_registry_data:/app/storage
    secrets:
      - source: pulsar_secret_key
        target: /run/secrets/pulsar_secret_key
        mode: 0400
      - source: db_user
        target: /run/secrets/db_user
        mode: 0400
      - source: db_password
        target: /run/secrets/db_password
        mode: 0400
    networks:
      - spec-template-network
      - pulsar-network
    depends_on:
      pulsar:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Workflow Engine - Orchestrates the entire flow
  workflow-engine:
    build:
      context: ./services/workflow_orchestrator
    environment:
      - PROJECT_SERVICE_URL=http://project_manager:8000
      - SPEC_REGISTRY_URL=http://spec-registry:8000
      - EVENT_BUS_URL=pulsar://pulsar:6650
      - EVENT_AGGREGATOR_URL=http://event-aggregator:8080
    depends_on:
      - spec-registry
      - pulsar
      - project_manager
      - event-aggregator
    networks:
      - spec-template-network
      - pulsar-network

  # Evolution Analyzer - Tracks template usage and suggests improvements
  evolution-analyzer:
    build:
      context: ../src/services/meta_learner
    environment:
      - SPEC_REGISTRY_URL=http://spec-registry:8000
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333
      - EVENT_BUS_URL=pulsar://pulsar:6650
      - EVENT_AGGREGATOR_URL=http://event-aggregator:8080
    depends_on:
      - spec-registry
      - vector-db
      - pulsar
      - event-aggregator
    networks:
      - spec-template-network
      - pulsar-network
