version: '3.8'

services:
  # API Gateway (Traefik)
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"  # Run as non-root user (use an appropriate UID:GID)
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/justinrussell/.traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /Users/justinrussell/.traefik/certs:/etc/traefik/certs:ro
      - /Users/justinrussell/.traefik/dynamic:/etc/traefik/dynamic:ro
      - /Users/justinrussell/.traefik/acme:/etc/traefik/acme
    networks:
      - api-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Authentication Sidecar
  auth-sidecar:
    build:
      context: ../src/api_gateway/auth-sidecar
    container_name: auth-sidecar
    secrets:
      - clerk_public_key
      - clerk_secret_key
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000,https://buildwithai.cloud
    volumes:
      # Mount the secrets directory as read-only files
      - Users/justinrussell/.docker-secrets/NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:/run/secrets/clerk_publishable_key:ro
      - Users/justinrussell/.docker-secrets/CLERK_SECRET_KEY:/run/secrets/clerk_secret_key:ro
      # Configuration volume if needed
      - ./config:/etc/auth-sidecar:ro
    networks:
      - api-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  # Neural Interpreter
  neural-interpreter:
    build:
      context: ./services/api_gateway/neural_interpretor
    container_name: neural-interpreter
    restart: unless-stopped
    volumes:
      - ../src/services/api_gateway/neural_interpretor/app/config:/app/config
      - ../certs/neural_interpretor://config/certs
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - LOG_LEVEL=INFO
    networks:
      - pulsar-network
    healthcheck:
      test: [ "CMD", "test", "-e", "/tmp/agent-health.txt" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - pulsar
      - auth-sidecar

  # Pulsar - Event Bus
  pulsar:
    image: apachepulsar/pulsar:4.0.3
    container_name: pulsar
    restart: unless-stopped
    ports:
      - "6650:6650"  # Pulsar binary protocol port
      - "8080:8080"  # Pulsar web service port
    volumes:
      - pulsar-data:/pulsar/data
      - ./certs:/pulsar/certs
      - ./infra/configs/pulsar:/pulsar/conf
      - ./bin/pulsar/setup.py:/pulsar/setup.py
    command: >
      /bin/bash -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone -nss -nfw"
    environment:
      - PULSAR_MEM=-Xms1g -Xmx1g
      - webServicePortTls=8443
      - tlsEnabled=true
      - tlsCertificateFilePath=Users/justinrussell/.pulsar/certs/pulsar.crt
      - tlsKeyFilePath=/pulsar/certs/pulsar.key
      - tlsTrustCertsFilePath=/pulsar/certs/ca.crt
      - authenticationEnabled=true
      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderTls
      - webSocketServiceEnabled=true
    networks:
      - pulsar-network
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Project Service - Manages projects and spec sheets
  project_manager:
    build:
      context: ../src/services/project_manager
    environment:
      - SPEC_REGISTRY=http://template-service:3001
      - POSTGRE_SERVICE=http://postgre-service:3002
      - EVENT_BUS_URL=pulsar://pulsar:6650
    depends_on:
      - spec_registry
      - postgre_service
      - pulsar
    networks:
      - spec-template-network
      - pulsar-network

  # Spec Generator - AI-assisted spec completion
    # Spec Registry Service
  spec-registry:
    build:
      context: ../src/services.spec-registry
      dockerfile: Dockerfile
      args:
        - SCHEMAS_VERSION=1.0.0
    container_name: spec-registry
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
      - ENABLE_EVENTS=true
      - BASE_DIR=/app/storage
    volumes:
      - spec_registry_data:/app/storage
    secrets:
      - source: pulsar_secret_key
        target: /run/secrets/pulsar_secret_key
        mode: 0400
    networks:
      - spec-template-network
      - pulsar-network
    depends_on:
      pulsar:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Storage Service - Handles persistence


  # Database - PostgreSQL for storing projects and completed specs
  database:
    image: postgres:17-bookworm
    secrets:
      - db_user
      - db_password
    container_name: specdb
    restart: unless-stopped
    environment:
      - POSTGRES_DB=specdb
      - POSTGRES_USER_FILE=/
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spec-template-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Vector Database - For template similarity search
  vector-db:
    image: qdrant/qdrant:2.31.0
    ports:
      - "6333:6333"
    volumes:
      - vector-db-data:/qdrant/storage
    networks:
      - spec-template-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Workflow Engine - Orchestrates the entire flow
  workflow-engine:
    build:
      context: ./services/workflow_orchestrator
    environment:
      - PROJECT_SERVICE_URL=http://project-service:3003
      - SPEC_GENERATOR_URL=http://spec-generator:3004
      - EVENT_BUS_URL=pulsar://pulsar:6650
    depends_on:
      - project-service
      - spec-generator
      - pulsar
    networks:
      - spec-template-network
      - pulsar-network

  # Evolution Analyzer - Tracks template usage and suggests improvements
  evolution-analyzer:
    build:
      context: ./services/meta_learner
    environment:
      - TEMPLATE_SERVICE_URL=http://template-service:3001
      - STORAGE_URL=http://storage-service:3002
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333
      - EVENT_BUS_URL=pulsar://pulsar:6650
    depends_on:
      - template-service
      - storage-service
      - vector-db
      - pulsar
    networks:
      - spec-template-network
      - pulsar-network

  # Monitoring Setup
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./services/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./services/prometheus/prometheus_rules.yaml:/etc/prometheus/prometheus_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - pulsar

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ./services/prometheus/alert_manager.yaml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:8.5.2
    container_name: grafana
    volumes:
      - ../src/services/grafana/app/provisioning/datasource:/etc/grafana/provisioning/datasources
      - ../src/services/grafana/app/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../src/services/grafana/app/dashboard_definitions:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_secure_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

  event-aggregator:
    build: .
    container_name: event-aggregator
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - EVENT_SYSTEM_DATABASE_TYPE=mongodb
      - EVENT_SYSTEM_DATABASE_URI=mongodb://mongodb:27017
      - EVENT_SYSTEM_DATABASE_NAME=event_system
      - EVENT_SYSTEM_EVENTS_PROVIDER=pulsar
      - EVENT_SYSTEM_EVENTS_SERVICE_URL=pulsar://pulsar:6650
      - EVENT_SYSTEM_VECTOR_DB_ENABLED=true
      - EVENT_SYSTEM_VECTOR_DB_TYPE=qdrant
      - EVENT_SYSTEM_VECTOR_DB_HOST=qdrant
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - pulsar
      - qdrant
    networks:
      - spec-template-network
      - pulsar-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring


secrets:
  clerk_public_key:
    file: /Users/justinrussell/.docker-secrets-codegen/next_public_clerk_publishable_key
  clerk_secret_key:
    file: /Users/justinrussell/.docker-secrets-codegen/clerk_secret_key
  db_user:
    file: /Users/justinrussell/.docker-secrets-codegen/db_user
  db_password:
    file: /Users/justinrussell/.docker-secrets-codegen/db_password
  openai_api_key:
    file: /Users/justinrussell/.docker-secrets-codegen/openai_api_key
  anthropic_api_key:
    file: /Users/justinrussell/.docker-secrets-codegen/anthropic_api_key
  pinecone_api_key:
    file: /Users/justinrussell/.docker-secrets-codegen/pinecone_api_key


networks:
  api-network:
    driver: bridge
  pulsar-network:
    driver: bridge
  spec-template-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  pulsar-data:
  prometheus_data:
  alertmanager_data:
  grafana_data:
  db-data:
  vector-db-data:
  storage-data: