# hmac-signer/config.yaml
# HMAC Signer Configuration
# Last updated: May 7, 2025

# HMAC authentication settings
hmac:
  key_id: neural-api-client
  secret_key_path: /run/secrets/hmac_secret_key
  expiry_seconds: 300

# Target services that require HMAC authentication
services:
  neural_interpreter:
    base_url: http://neural-interpreter:8080
    timeout_ms: 10000
  pulsar_websocket:
    base_url: http://pulsar:8080
    timeout_ms: 5000

# Retry policy
retry:
  max_attempts: 3
  initial_backoff_ms: 1000
  max_backoff_ms: 10000
  backoff_multiplier: 2.0

# Logging
logging:
  level: info
  format: json
  mask_sensitive_data: true